create view v_espen_bf_lf_cov_3_cap_202211_v2_1 as 
select

id, 
code_equipe "Code Equipe", 
district "District",
numero_grappe "Num. Grappe", 
code_grappe "Code Grappe", 
numero_menage "Num. Ménage", 
age "Age",
sexe "Sexe", 
niveau_instruction "Niveau instruction",
duree_resident "Durée Résicence en Année", 
duree_resident_mois "Durée Résicence en Mois", 
entendu_parler_oncho "Entendu Parler ONCHO", 
inquiet "Inquiet", 
manifestations "Manifestation", 
autres_manisfestations "Autres Manifestations",
mode_transmission  "Mode Transmission",
autres_transmission "Autres Transission",
prevention "Prévention", 
autres_prevention "Autres Pprésention", 
cnce_aveugle "Connaissance Aveugle", 
nombre_aveugle "Nombre Aveugle", 
informe "information", 
canaux_information "Canaux information", 
autres_canaux_information "Autres Canaux information",
nbre_resident_menage "Nbr résident Ménage",
nbre_resident_moins5ans "Nbr résident moin 4 ans", 
resident_non_traite "Résident non traité", 
nbre_resident_non_traite "Nbr. Résident non traités", 
satisfaction "Satisfaction", 
insatisfaction "insatisfaction", 
perception_dc "Perception DC",
suggestions "Suggestion", 
gps_lat "Lat", 
gps_lng "long", 
 gps_acc "Précision", 
 commentaires "Commentaites",
 "start" "Date"

FROM public.espen_bf_lf_cov_3_cap_202211_v2_1 k
