-- public.v_espen_lr_sch_sth_impact_202401_3_kato_katz_v2_1 source

CREATE OR REPLACE VIEW public.v_espen_lr_sch_sth_impact_202401_3_kato_katz_v2_1
AS SELECT c.id,
    k.k_recorder,
    k.k_district,
    k.k_location,
    k.k_school_name,
    k.k_school_id,
    c.k_add_result,
    c.k_code_id,
    c.k_sch_man_sa,
    c.k_sch_man_sb,
    c.k_sch_man_intensity,
    c.k_sch_man_heavy_intensity,
    c.k_sch_man_moderate_intensity,
    c.k_ascaris_lumb_sa,
    c.k_ascaris_lumb_sb,
    c.k_ascaris_lumb_intensity,
    c.k_ascaris_lumb_heavy_intensity,
    c.k_ascaris_lumb_moderate_intensity,
    c.k_hookworm_sa,
    c.k_hookworm_sb,
    c.k_hookworm_intensity,
    c.k_hookworm_heavy_intensity,
    c.k_hookworm_moderate_intensity,
    c.k_trichuris_sa,
    c.k_trichuris_sb,
    c.k_trichuris_intensity,
    c.k_trichuris_heavy_intensity,
    c.k_trichuris_moderate_intensity,
    c.k_sch_hae_sa,
    c.k_sch_hae_sb,
    c.k_other_name_1,
    c.k_other_quantity_1a,
    c.k_other_quantity_1b,
    c.k_remarks,
    k.k_start
   FROM espen_lr_sch_sth_impact_202401_3_kato_katz_v2_1 k,
    espen_lr_sch_sth_impact_202401_3_kato_katz_v2_1_lr_k_202401_v2_ c
  WHERE k.id::text = c.parent_id;