-- public.v_espen_civ_oncho_bsa_2501_1_river_assessment_all source

CREATE OR REPLACE VIEW public.v_espen_civ_oncho_bsa_2501_1_river_assessment_all
AS SELECT s.id,
    s.s_recorder_id,
    s.s_region,
    s.s_district,
    s.s_district_id,
    s.s_health_facility,
    s.s_health_facility_other,
    s.s_site,
    s.s_site_id,
    s.s_population,
    s.s_simulies_present,
    s.s_tdm_pratique,
    s.s_date_tdm_annee,
    s.s_date_tdm_mois,
    s.s_gps_lat,
    s.s_gps_lng,
    s.s_gps_acc,
    s.s_start
   FROM espen_civ_oncho_bsa_2501_1_river_assessment_oem s
UNION ALL
 SELECT s.id,
    s.s_recorder_id,
    s.s_region,
    s.s_district,
    s.s_district_id,
    s.s_health_facility,
    s.s_health_facility_other,
    s.s_site,
    s.s_site_id,
    s.s_population,
    s.s_simulies_present,
    s.s_tdm_pratique,
    s.s_date_tdm_annee,
    s.s_date_tdm_mois,
    s.s_gps_lat,
    s.s_gps_lng,
    s.s_gps_acc,
    s.s_start
   FROM espen_civ_oncho_bsa_2501_1_river_assessment_prestop s
UNION ALL
 SELECT s.id,
    s.s_recorder_id,
    s.s_region,
    s.s_district,
    s.s_district_id,
    s.s_health_facility,
    s.s_health_facility_other,
    s.s_site,
    s.s_site_id,
    s.s_population,
    s.s_simulies_present,
    s.s_tdm_pratique,
    s.s_date_tdm_annee,
    s.s_date_tdm_mois,
    s.s_gps_lat,
    s.s_gps_lng,
    s.s_gps_acc,
    s.s_start
   FROM espen_civ_oncho_bsa_2501_1_river_assessment_stop24 s
UNION ALL
 SELECT s.id,
    s.s_recorder_id,
    s.s_region,
    s.s_district,
    s.s_district_id,
    s.s_health_facility,
    s.s_health_facility_other,
    s.s_site,
    s.s_site_id,
    s.s_population,
    s.s_simulies_present,
    s.s_tdm_pratique,
    s.s_date_tdm_annee,
    s.s_date_tdm_mois,
    s.s_gps_lat,
    s.s_gps_lng,
    s.s_gps_acc,
    s.s_start
   FROM espen_civ_oncho_bsa_2501_1_river_assessment_stop25 s;