-- public.v_espen_tz_sch_sth_impact_2405_3_kato_katz source
 create view v_espen_tz_sch_sth_impact_2405_3_kato_katz as
 SELECT c.id,
    k.meta_instance_id,
    k.k_recorder,
    k.k_district,
    k.k_ward,
    k.k_site,
    k.k_site_id,
    c.k_add_result,
    c.k_barcode_id,
    c.k_hookworm_sa,
    c.k_hookworm_sb,
    c.k_hookworm_intensity,
    c.k_hookworm_heavy_intensity,
    c.k_hookworm_moderate_intensity,
    c.k_ascaris_lumb_sa,
    c.k_ascaris_lumb_sb,
    c.k_ascaris_lumb_intensity,
    c.k_ascaris_lumb_heavy_intensity,
    c.k_ascaris_lumb_moderate_intensity,
    c.k_trichuris_sa,
    c.k_trichuris_sb,
    c.k_trichuris_intensity,
    c.k_trichuris_heavy_intensity,
    c.k_trichuris_moderate_intensity,
    c.k_sch_man_sa,
    c.k_sch_man_sb,
    c.k_sch_man_intensity,
    c.k_sch_man_heavy_intensity,
    c.k_sch_man_moderate_intensity,
    c.k_sch_hae_sa,
    c.k_sch_hae_sb,
    c.k_other_eggs,
    c.other_eggs_name,
    c.other_eggs_sa,
    c.other_eggs_sb,
    c.k_remarks,
    k.k_start,
    'v4'::text AS k_version
   FROM espen_tz_sch_sth_impact_2405_3_kato_katz k,
    public.espen_tz_sch_sth_impact_2405_3_kato_katz_tz_st_k_2405 c
  WHERE k.id::text = c.parent_id