create view v_espen_bf_oncho_cdticov_2410_2_couverture_v2_1 as

SELECT 

c.id,
p.p_equipe, 
p.p_district, 
p.p_code_grappe,
p.p_numero_menage,
c.parent_id,

c.p_numero_enquete, 
c.p_code_enquete,
c.p_repondant, 
c.p_age, 
c.p_age_en_mois, 
c.p_sexe, 
c.p_etude, 
c.p_duree_sejour, 
c.p_dejatraite, 
c.p_nb_ivm_avale, 
c.p_jamais_ivm, 
c.p_autres_raisons, 
c.p_recu_ivm, 
c.p_pourquoi_pas_recu_ivm, 
c.p_raisons_absence, 
c.p_autre_traitement, 
c.p_lieu_autrement_traitement, 
c.p_avale_ivm, 
c.p_nb_comp_avale, 
c.p_prise_supervisee, 
c.p_pourquoi_avale, 
c.p_autre_pourquoi_avale, 
c.p_pourquoi_pas_avale, 
c.p_autres_pourquoi_pas_avale, 
c.p_lieux, 
c.p_autre_lieux, 
c.p_prise_taille, 
c.p_effet_indesirable, 
c.p_type_effet_indesirable, 
c.p_autre_effet_indesirable, 
c.p_combien_de_temps, 
c.p_informe, 
c.p_canaux_information, 
c.p_autres_canaux_information, 
c.p_satisfait, 
c.p_insatisfaction, 
c.p_suggestions, 
c.p_taille, 
c.p_traitementparlequipe, 
c.p_notes, 
p.p_debut_enreg

FROM espen_bf_oncho_cdticov_2410_2_couverture_v2_1 p, espen_bf_oncho_cdticov_2410_2_couverture_v2_1_bf2410_2 c
where p.id = c.parent_id::int

