create view v_espen_bj_sct_lf_1_cov_2406_v3_3 as

SELECT 

c.id, 
p.recorder_id,
p."date",
p.commune,
p.arrondissement, 
p.village,
p.village_id, 
p.gps_lat,
p.gps_lng, 
p.gps_acc,
p.type_soumission,
p.q0_index_menage, 
p.q0_numero_menage, 
p.q1_nbre_personne_ds_menage,
p.q1_nbre_eas_ds_menage, 
p.q2_vis_ds_cummunaute_12_mois,
p.q3_src_eau_potable_maison, 
p.q3_src_eau_potable_maison_autre, 
p.q4_toilette_maison, 
p.q4_toilette_maison_autre, 
p.q5_condition_toilette, 
p.q6_existe_dispositif_lavage_main, 
p.q7_profession, 
p.q7_profession_autre, 
p.q8a_plan_eau_douce_com, 
p.q8b_tps_allez_retout_eau_douce,
p.q9_src_eau_se_desseche, 
p.q10_se_baigne_eau_douce, 
p.q11_lessive_eau_douce, 

c.parent_id,
c.q12_code_id, 
c.q12_sex, 
c.q13_age, 
c.q14_niveau_etude, 
c.q14_niveau_etude_other, 
c.q15_nbr_fois_vas_ecole, 
c.q16_repondant_a_maison, 
c.q17_repondant_repond_lui_meme, 
c.q18_repondant_a_chaussure, 
c.q19_repondant_ne_dans_com, 
c.q19_tps_vis_dans_com, 
c.q20_repondant_dans_com_2024,
c.q21_raison_repondant_pas_com_2024, 
c.q21_raison_repondant_pas_com_2024_autre, 
c.q22_repondant_savait_tdm, 
c.q23_moment_recu_info, 
c.q24_comment_entendu_tdm, 
c.q24_comment_entendu_tdm_autre, 
c.q25_propose_pzq, 
c.q26_raison_pas_propose_pzq,
c.q26_raison_pas_propose_pzq_autre, 
c.q27_qui_a_donne_pzq, 
c.q27_qui_a_donne_pzq_autre,
c.q28_avale_pzq, 
c.q29_raison_pas_avale_pzq, 
c.q29_raison_pas_avale_pzq_autre,
c.q30_raison_avale_pzq, 
c.q30_raison_avale_pzq_autre, 
c.q31_avale_pzq_devant_distributeur,
c.q32_effet_secondaire_pzq,
c.q33_type_effet_secondaire_pzq, 
c.q34_nb_fois_participe_tdm_sch, 
c.q35_pourquoi_jamais_participe, 
c.q35_pourquoi_jamais_participe_autre, 
c.q36_entendu_parler_sch, 
c.q37_ou_entendu_parler_sch,
c.q37_ou_entendu_parler_sch_autre, 
c.q38_transmission_sch,
c.q38_transmission_sch_autre, 
c.q39_symptome_sch, 
c.q39_symptome_sch_autre, 
c.q40_prevention_sch, 
c.q40_prevention_sch_autre, 
c.q41_traitement_pzq,
c.q41_traitement_pzq_autre,
c.q42_selectionner_bandelette,
c.q43_gradation, 
c.commentaires, 
p."start" c_start

FROM espen_bj_sct_lf_1_cov_2406_v3_3 p, espen_bj_sct_lf_1_cov_2406_v3_3_bj_c_2406_v33 c

where p.id = c.parent_id::int

union all

SELECT 

c.id, 
p.recorder_id,
p."date",
p.commune,
p.arrondissement, 
p.village,
p.village_id, 
p.gps_lat,
p.gps_lng, 
p.gps_acc,
p.type_soumission,
p.q0_index_menage, 
p.q0_numero_menage, 
p.q1_nbre_personne_ds_menage,
p.q1_nbre_eas_ds_menage, 
p.q2_vis_ds_cummunaute_12_mois,
p.q3_src_eau_potable_maison, 
p.q3_src_eau_potable_maison_autre, 
p.q4_toilette_maison, 
p.q4_toilette_maison_autre, 
p.q5_condition_toilette, 
p.q6_existe_dispositif_lavage_main, 
p.q7_profession, 
p.q7_profession_autre, 
p.q8a_plan_eau_douce_com, 
p.q8b_tps_allez_retout_eau_douce,
p.q9_src_eau_se_desseche, 
p.q10_se_baigne_eau_douce, 
p.q11_lessive_eau_douce, 

c.parent_id,
c.q12_code_id, 
c.q12_sex, 
c.q13_age, 
c.q14_niveau_etude, 
c.q14_niveau_etude_other, 
c.q15_nbr_fois_vas_ecole, 
c.q16_repondant_a_maison, 
c.q17_repondant_repond_lui_meme, 
c.q18_repondant_a_chaussure, 
c.q19_repondant_ne_dans_com, 
c.q19_tps_vis_dans_com, 
c.q20_repondant_dans_com_2024,
c.q21_raison_repondant_pas_com_2024, 
c.q21_raison_repondant_pas_com_2024_autre, 
c.q22_repondant_savait_tdm, 
c.q23_moment_recu_info, 
c.q24_comment_entendu_tdm, 
c.q24_comment_entendu_tdm_autre, 
c.q25_propose_pzq, 
c.q26_raison_pas_propose_pzq,
c.q26_raison_pas_propose_pzq_autre, 
c.q27_qui_a_donne_pzq, 
c.q27_qui_a_donne_pzq_autre,
c.q28_avale_pzq, 
c.q29_raison_pas_avale_pzq, 
c.q29_raison_pas_avale_pzq_autre,
c.q30_raison_avale_pzq, 
c.q30_raison_avale_pzq_autre, 
c.q31_avale_pzq_devant_distributeur,
c.q32_effet_secondaire_pzq,
c.q33_type_effet_secondaire_pzq, 
c.q34_nb_fois_participe_tdm_sch, 
c.q35_pourquoi_jamais_participe, 
c.q35_pourquoi_jamais_participe_autre, 
c.q36_entendu_parler_sch, 
c.q37_ou_entendu_parler_sch,
c.q37_ou_entendu_parler_sch_autre, 
c.q38_transmission_sch,
c.q38_transmission_sch_autre, 
c.q39_symptome_sch, 
c.q39_symptome_sch_autre, 
c.q40_prevention_sch, 
c.q40_prevention_sch_autre, 
c.q41_traitement_pzq,
c.q41_traitement_pzq_autre,
c.q42_selectionner_bandelette,
c.q43_gradation, 
c.commentaires, 
p."start" c_start

FROM espen_bj_sct_lf_1_cov_2406_v3_2 p, espen_bj_sct_lf_1_cov_2406_v3_2_bj_c_2406_32 c

where p.id = c.parent_id::int



