SELECT u.id,
    u.u_recorder,
    u.u_drshp,
    u.u_district,
    u.u_csps,
    u.u_consentement,
    u.u_code_site,
    u.u_numero_enquete,
    u.u_numero_enquete_complet,
    u.u_echantilliontraite,
    u.u_volumeurine,
    u.u_microhematurie,
    u.u_graduation,
    u.u_echantillionpositif,
    u.u_oeufs_a,
    u.u_oeufs_b,
    u.u_commentaires,
    u.u_start
   FROM espen_bf_202301_sch_impact_assessment_4_resultat_urines_v3 u;